//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_DEMO.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class List_Of_Notes
    {
        public string Username { get; set; }
        public int NotesOrder { get; set; }
        public string NotesHeader { get; set; }
        public string NotesContent { get; set; }
        public string NoteTag { get; set; }
        public string FontFamily { get; set; }
        public Nullable<int> FontSize { get; set; }
        public string NoteColor { get; set; }
        public string NotePictureName { get; set; }
        public string NoteDrawPictureName { get; set; }
    
        public virtual User User { get; set; }
    }
}
