//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_DEMO.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class List_Of_TrashBin
    {
        public string Username { get; set; }
        public int TrashOrder { get; set; }
        public string TrashHeader { get; set; }
        public string TrashContent { get; set; }
        public string TrashTag { get; set; }
        public string FontFamily { get; set; }
        public Nullable<int> FontSize { get; set; }
        public string TrashColor { get; set; }
        public string TrashPictureName { get; set; }
        public string TrashDrawPictureName { get; set; }
    
        public virtual User User { get; set; }
    }
}
