//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_DEMO.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class List_Of_ImportantNote
    {
        public string Username { get; set; }
        public int ImportantOrder { get; set; }
        public string ImportantHeader { get; set; }
        public string ImportantContent { get; set; }
        public string ImportantTag { get; set; }
        public string FontFamily { get; set; }
        public Nullable<int> FontSize { get; set; }
        public string NoteColor { get; set; }
        public string NotePictureName { get; set; }
        public string NoteDrawPictureName { get; set; }
        public int NoteOrder { get; set; }
    
        public virtual User User { get; set; }
    }
}
