//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_DEMO.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WindowProgrammingSQLEntities : DbContext
    {
        public WindowProgrammingSQLEntities()
            : base("name=WindowProgrammingSQLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<List_Of_ImportantNote> List_Of_ImportantNote { get; set; }
        public virtual DbSet<List_Of_Notes> List_Of_Notes { get; set; }
        public virtual DbSet<List_Of_TrashBin> List_Of_TrashBin { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
